### ISSUE TITLE
Best way to use in iOS project?

### ISSUE THREAD

**Issue by eliotfowler** [pointfreeco/swift-prelude#104]
Hey thanks so much for open-sourcing this library, it looks awesome. I follow the kickstarter project and was pleased to see that this feels like a nice iteration on many of the ideas you introduced there. After watching your latest episode and checking out Overture, I am interested in trying to integrate some of the operators and functions in this project into my project. I am under the impression that I cannot yet use swift package manager with iOS code*, which I see is the recommended approach in your readme.

I have tried adding the entire project as a git submodule, but that fails due to the duplicate file names.

I also went down the path of forking and changing the filenames, but I realized there are a couple of points where you call Prelude.map or something to that effect and realized I was probably going down a rabbit hole that I didn't want to continue down.

I see a couple points in the code where you are checking for the iOS platform and including specific code, so I believe you're aiming to support that. I would really appreciate it if you can point me down the correct path so I can give some of these operators a whirl.

Thanks again for the awesome library and videos!

\* According to some reports on the web, I may be wrong on this. Even the articles that claim to show a workaround say it's quite a challenge though. If this is still the best approach for iOS, that's totally acceptable to me!

**Comment by stephencelis** [comment]
Hey @eliotfowler! Thanks for your interest in Prelude! It's very experimental still, which is why we haven't given it much of a story for installation yet (compared to Overture). If you're still interested in giving the current API a go (which may change a lot in the future, though probably not in the near future), filenames only need to be the same in a given module, so one solution (for now) would be to submodule the project, `cd` into it, and run `swift package generate-xcodeproj`. This'll generate a project file that you can drag into your iOS project. Then you just need to embed the library in your binary as you would with any framework.

**Comment by pteasima** [comment]
Haha I was thinking the exact same thing a couple days ago. SPM on ios workaround looks a pain, embedding project looks better but ultimately I decided to not do it an keep fingers crossed for some kind of spm ios announcement on wwdc :D 

Btw @eliotfowler I went down the rabbit hole some time ago when I imported the source code for the Swift 4.0 version of this library into a Swift 4.1 playground. The rabbit hole is about 1-1.5h deep ;)

**Comment by pteasima** [comment]
Sorry I gave you half the info. I used it in Swift Playgrounds for ipad so I had to copy the source files and change Prelude. to NameOfPlayground_Framework. etc etc, plus I had clashes with other libraries. An inteteresting note to take from this is that when you have two files of the same name in different subfolders of a playground’s Sources directory, xcode gives an “invalid developer path” error.

Also I should add: 1h deep but worth every second :)

**Comment by stephencelis** [comment]
Oh interesting! We've been wanting to play around with iPad playgrounds but haven't yet. Will keep that in mind 😅

**Comment by eliotfowler** [comment]
@stephencelis Awesome, thanks for the explanation! It makes total sense to me not to spend time writing docs on integration when the API is still experimental. I just got excited after poking through the pointfree code and watching the videos and figured I'd give it a go.

Thanks again for all the hard work! I look forward to following along and maybe even contributing in the future.
