### ISSUE TITLE
Fail to build

### ISSUE THREAD

**Issue by amadeu01** [pointfreeco/swift-prelude#128]
I'm trying to build the project.

I tried to clone the repo and then run `swift build` I'm getting 

```
error: conditional conformance of type 'Tagged<Tag, RawValue>' to protocol 'Numeric' does not imply conformance to inherited protocol 'AdditiveArithmetic'
extension Tagged: Numeric where RawValue: Numeric {
```

Is there some other step to build the project?

**Comment by amadeu01** [comment]
It might be due to Xcode update. But, I'm compiling with swift 4.2. 

I guess it might be related to this.
https://github.com/apple/swift-evolution/blob/master/proposals/0233-additive-arithmetic-protocol.md

**Comment by stephencelis** [comment]
@amadeu01 This seems to be the key:

https://twitter.com/johannesweiss/status/1110617911742345218

The Swift 5 compiler still works differently when it runs in Swift 4.2 mode :/ We recently upgraded Tagged to Swift 5 and will be updating Prelude in the next week or so. We have a `swift-5` branch going but need to get its tests passing, etc. For future releases we'll try to add these compiler checks in to avoid these kinds of problems.

**Comment by amadeu01** [comment]
Hi 👋 @stephencelis 

I tried the `swift-5` branch, but still couldn't build. Then I followed the instructions of adding 

```
#if compiler(<5)
#endif
```

Where it could not compile, it worked fine so far.

**Comment by maximkrouk** [comment]
Hi, latest release is `0.1.2` from `19.06.2017` and it fails to build, maybe it is worth releasing a new version already? 😅

**Comment by stephencelis** [comment]
@maximkrouk We may do a "ceremonial" release in a bit, but are going to do a lil repo cleanup in the meantime, including closing out this quite old issue :)
