### ISSUE TITLE
tmp and tmp2 in Tuple.swift

### ISSUE THREAD

**Issue by JimRoepcke** [pointfreeco/swift-prelude#131]
https://github.com/pointfreeco/swift-prelude/blob/8cbc93417c7dca20124d25ab9f2c0d31999e26ec/Sources/Tuple/Tuple.swift#L35-L36

Are these identifiers intended to be in this file? If so, what is their purpose?

**Comment by mbrandonw** [comment]
oops no, that is test code that accidentally snuck in. it should be removed.

thanks for the heads up!
