### ISSUE TITLE
Tuple.init(a:b:c:) produces warning in Xcode 10.2.1

### ISSUE THREAD

**Issue by JimRoepcke** [pointfreeco/swift-prelude#133]
On `master` and the `swift-5` branch:

https://github.com/pointfreeco/swift-prelude/blob/3f06eada6a03c8cc4638892be6eec925ce2bb1d7/Sources/Tuple/Tuple.swift#L28-L33

This produces the following warning in Xcode 10.2.1:

`Neither type in same-type constraint ('Tuple<A, B>' or 'Tuple<A, Tuple<B1, Tuple<C, Unit>>>') refers to a generic parameter or associated type`

I'm trying to eliminate warnings in my codebase to turn on warnings-as-errors and so far I haven't figured out how to change the code to not have a warning or error and maintain the same semantics (which I admit are not 100% clear to me -- I think I understand what's intended but I don't want to assume I'm right).

Perhaps I should just remove this extension/initializer in my codebase for the time being until it's updated/removed here? If this is a useful initializer for users of the `Tuple` type, it'd be great to get it building without warnings. Since those `tmp` and `tmp2` were removed there are no uses of it I can see.

Thanks for any guidance you can offer. No rush at all, I know the `swift-5` branch is still a WIP.

**Comment by mbrandonw** [comment]
I don't have time to look into the error right now, _but_ that initializer is `internal` and not used at all. I think it was apart of the test code that had introduced those `tmp` variables, and so we can just delete it. The better way to create tuples is with the `.*.` operator anyway, not this initializer.
