### ISSUE TITLE
Clamp includes upperBound in possible results

### ISSUE THREAD

**Issue by seanwoodward** [pointfreeco/swift-prelude#135]
the `clamp` functions in [Prelude/Comparable.swift](https://github.com/pointfreeco/swift-prelude/blob/7056dd00e89cda09ee4b64bc1ab4f6f9c013a61c/Sources/Prelude/Comparable.swift#L67-L77) return allow the upper bound to be returned, but the range specifically excludes that upper bound.
```swift
false == (1..<10).contains(10)
10 == clamp(1..<10)(10)
```
Consider the following:
```swift
public func clamp<T>(_ to: CountableClosedRange<T>) -> (T) -> T {
  return { element in
    return min(to.upperBound, max(to.lowerBound, element))
  }
}

public func clamp<T>(_ to: CountableRange<T>) -> (T) -> T {
  return clamp(to.lowerBound...max(to.lowerBound, to.upperBound.advanced(by: -1)))
}

public func clamp<T>(_ to: ClosedRange<T>) -> (T) -> T {
  return { element in
    min(to.upperBound, max(to.lowerBound, element))
  }
}
```
I don't think it possible to determine an exact value lower than the upperBound of a Range. Even if `T` was `Strideable`, the distance of the stride would need to be known.

**Comment by stephencelis** [comment]
Thanks! Sorry for waiting so long to fix :) Hopefully didn't have any unintended consequences downstream.

**Comment by seanwoodward** [comment]
Cheers
