### ISSUE TITLE
Add new git tag to fetch latest version for Swift Package Manager

### ISSUE THREAD

**Issue by Arcovv** [pointfreeco/swift-prelude#138]
I really love this framework but can not retrieve the latest version of it.

I think the problem is git tag version tagged at an old state.

**Comment by Viranchee** [comment]
Same, need tags

**Comment by thomjordan** [comment]
I'm having the same issue now in May 2020, the same as it was last year when I tried to use it.. Please fix this!

**Comment by Viranchee** [comment]
Hey use the master branch or latest branch in Swift package manager, it works fine

**Comment by sukhanovevgeniy96** [comment]
> Hey use the master branch or latest branch in Swift package manager, it works fine

it doesn't work if you use prelude as dependencies for your own swift package. 
I have error like this
because package <mypackage> is required using a version-based requirement and it depends on unversion package swift-prelude and root depends on <mypackage> 1.0.0, version solving failed.

**Comment by stephencelis** [comment]
Sorry for the silence from maintenance :) We've always advertised Prelude an "alpha/experimental/unstable" set of tools that we apply to our own exploration and projects, and we really do recommend maintaining downstream forks of any code that is useful to you. We may cut more releases in the future, but would not recommend relying directly on this repo as a source of truth. Going to close this out, and will try to make the README more clear soon.
