### ISSUE TITLE
Throwing Functions

### ISSUE THREAD

**Issue by gkaimakas** [pointfreeco/swift-prelude#144]
More of a question, not an issue,

Which is the best approach in handling throwing functions? 
I can't any way to compose throwing functions  in `Prelude` so I am a bit confused.

In my codebase I've taken into account every possible case like so:

```


public func >>> <A, B, C>(f: @escaping (A) -> B,
                          g: @escaping (B) -> C)
    -> (A) -> C {

  return { a in
    g(f(a))
  }
}

public func >>> <A, B, C>(f: @escaping (A) throws -> B,
                          g: @escaping (B) -> C)
    -> (A) throws -> C {

  return { a in
    g(try f(a))
  }
}

public func >>> <A, B, C>(f: @escaping (A) -> B,
                          g: @escaping (B) throws -> C)
    -> (A) throws -> C {

  return { a in
    try g(f(a))
  }
}

public func >>> <A, B, C>(f: @escaping (A) throws -> B,
                          g: @escaping (B) throws -> C)
    -> (A) throws -> C {

  return { a in
    try g( try f(a))
  }
}
```

but I am not sure if this is the best approach

**Comment by gkaimakas** [comment]
It appears you had it covered in a later episode 😊


https://www.pointfree.co/collections/map-zip-flat-map/flat-map/ep44-the-many-faces-of-flat-map-part-3

**Comment by stephencelis** [comment]
Ha sorry for the radio silence here! We must've lost track of things. Thanks for taking the time to post, though! This is definitely something that we think should probably be avoided for confusion. We're also considering getting rid of the `rethrows` and `throws` overloads in Overture in general. We've found that they can lead to ambiguity and that it might be better to work with `Result` types when working with Overture :)
